- name: Installs memcached
  apt:
    name: memcached
    state: present

- name: Push memcached config
  template:
    src: "../templates/memcached.conf.j2"
    dest: /etc/memcached.conf
    mode: 0644
  notify: Restart memcached
